Path/ai-lab-chat
observability-lab-cse/observability-lab pull request #192
Opened 2024-09-17 21:47 UTC by osama18

Added the chat function to be called from chat endpoint. the chat function will read api key and endpoint from env variable

2024-09-18 19:09 UTC, MahrRah requested changes

2024-09-18 19:09 UTC, MahrRah commented on sample-application/device-assistant/chat.py
> +        response = requests.post(ENDPOINT, headers=headers, json=payload)
Nit: ENDPOINT could be little more descriptive

2024-09-19 17:55 UTC, MahrRah commented on sample-application/device-assistant/README.md
> +poetry run python main.py
```suggestion
```sh
cd sample-application/device-assistant/
poetry run python main.py
```
```

2024-09-19 17:55 UTC, MahrRah commented on sample-application/device-assistant/README.md
> +OPENAI_API_ENDPOINT: The endpoint for OpenAI's API.
```suggestion
```txt
OPENAI_API_KEY=<your-openai-api-key>
OPENAI_API_ENDPOINT=<your-openai-api-endpoint>
```
```

2024-09-19 17:55 UTC, MahrRah commented on test.http
> +}
This might not work with the new changes and needs to be `question`, right?

2024-09-24 07:54 UTC, MaggieSalak commented on sample-application/device-assistant/README.md
> +
```suggestion
```
```

2024-09-27 07:26 UTC, MaggieSalak commented on sample-application/device-assistant/README.md
> +
updated

2024-09-27 07:26 UTC, MaggieSalak approved these changes

2024-09-30 07:28 UTC, merged